---
gateway : "192.168.1.1"
dns: "192.168.1.148"

vms_to_create:
 - name: "main"
   ip_address: "192.168.1.120/24"
   memory: "1024"

 - name: "secondary"
   ip_address: "192.168.1.121/24"
   memory: "1024"